spring:
  jpa:
    properties:
      hibernate:
        format_sql: true

jwt:
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 604800

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: account

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.gooddaytaxi.account.adapter.web,com.gooddaytaxi.account.presentation.controller
